// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqfigcoevlyvechyvzja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZmlnY29ldmx5dmVjaHl2emphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjE5NjcsImV4cCI6MjA1OTEzNzk2N30.cGrc08Qe2DwKSXBMum7VMsXp2mIOOt5SzVuW49Mi5Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);